### ISSUE TITLE
Users with many ssh keys will need to set an SSH config

### ISSUE THREAD

**Issue by jfrost-mo** [MetOffice/git-novice#57]
Users with more than a few SSH keys will find themselves rejected by GitHub for trying too many incorrect keys, and will need to add a section to their SSH config to tell SSH what key to use to connect to GitHub.

In `~/.ssh/config` add the following:
```ssh-config
Host github.com
  IdentityFile ~/.ssh/id_ed25519_github
```

**Comment by astroDimitrios** [comment]
Some partner orgs may need this anyway so I think we say if you have many ssh keys or having trouble authenticating add this in.
