### ISSUE TITLE
Move branches to the morning git section

### ISSUE THREAD

**Issue by astroDimitrios** [MetOffice/git-novice#65]
Complete change of the lesson to move branches to the morning as the very first topic - this avoids us committing to main.
Link to the intro as branches are fundamental to using Git.

Move to the forecast branch and make changes in the morning.

Alter the GitHub section to push this to remote and merge into main via PR.
Update local main from GitHub main as normal.

**Comment by ehogan** [comment]
Can I also add to this:

Discuss naming of branches and uniqueness, e.g. add the issue number to the start of a branch name to minimise the risk of creating a branch with the same name as someone else!
