### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by wxtim** [MetOffice/git-novice#75]
Some users get errors from autocomplete, probably caused by not having `~/git-prompt.sh`.

Should this be installed.

**Comment by astroDimitrios** [comment]
@wxtim A lot of errors were from people not reading the instructions properly - maybe we should make the part which says `your intructor will let you know what the GIT_PROMPT_PATH is` a caution callout so it is more visible.

The correct paths for the Met Office are included in the calendar invites for the training.

- [ ] Make it clearer that the path is given to them by the instructor
- [ ] Add the paths to our SharePoint training pages as well
- [ ] Only set PROMPT_COMMAND or PS1 not both?
- [ ] Add in optional line break
- [ ] Make the section an **optional** setup step

**Comment by wxtim** [comment]
> The correct paths for the Met Office are included in the calendar invites for the training.

Not obvious IMO
